
- name: Instalacion de un server Apache.
  hosts: apache
  become: true

  tasks:

    - name: Instalar Apache.
      dnf:
        name: httpd
        state: latest
    
    - name: Habilitar servicio
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Escribir un index.html
      copy:
        src: ./index.html
        dest: /var/www/html/index.html

- name: Instalacion de un server Nginx.
  hosts: nginx
  become: true
  tasks:

      - name: Instalar Nginx.
        dnf:
          name: nginx
          state: latest
      
      - name: Habilitar servicio
        systemd:
          name: nginx
          state: started
          enabled: yes

      - name: Escribir un index.html
        copy:
          src: ./index.html
          dest: /usr/share/nginx/html/index.html


    

